/**
 * SKILL.md serialization.
 *
 * Company Brain's output format is an "Agent Skill": a folder named after
 * the skill containing a SKILL.md file. SKILL.md = YAML frontmatter (`name`,
 * `description`) + a markdown body holding the procedure and its cited sources.
 *
 * This module is deliberately dependency-free and reused by both the skill-audit
 * CLI and (later) the product's publish layer.
 */

export interface SkillSource {
  url: string;
  title: string;
}

export interface SkillDraft {
  /** lowercase-hyphenated id, e.g. "handle-refund-requests" */
  slug: string;
  /** human title, e.g. "Handle refund requests" */
  title: string;
  /** one-line trigger description that goes in the frontmatter */
  description: string;
  /** the procedure body in markdown (no frontmatter, no Sources section) */
  body: string;
  /** documents this skill was derived from */
  sources: SkillSource[];
  /** model's self-reported confidence: high | medium | low */
  confidence?: "high" | "medium" | "low";
}

/** Turn arbitrary text into a safe lowercase-hyphenated slug. */
export function slugify(input: string): string {
  return input
    .toLowerCase()
    .normalize("NFKD")
    .replace(/[^\w\s-]/g, "")
    .trim()
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 64) || "untitled-skill";
}

/** Escape a value for safe use inside a single-line YAML double-quoted string. */
function yamlString(value: string): string {
  return `"${value.replace(/\\/g, "\\\\").replace(/"/g, '\\"').replace(/\n/g, " ").trim()}"`;
}

/**
 * Serialize a draft into a complete SKILL.md document string.
 * The frontmatter follows the Agent Skills convention (name + description);
 * the body appends a machine-traceable Sources section so every claim is
 * auditable back to the document it came from.
 */
export function serializeSkill(draft: SkillDraft): string {
  const fm: string[] = [
    "---",
    `name: ${draft.slug}`,
    `description: ${yamlString(draft.description)}`,
    "---",
    "",
  ];

  const parts: string[] = [fm.join("\n"), `# ${draft.title}`, "", draft.body.trim(), ""];

  if (draft.confidence) {
    parts.push(`> **Extraction confidence:** ${draft.confidence}. Review before approving.`, "");
  }

  if (draft.sources.length > 0) {
    parts.push("## Sources", "");
    for (const s of draft.sources) {
      parts.push(`- [${s.title || s.url}](${s.url})`);
    }
    parts.push("");
  }

  parts.push(
    "---",
    "_Draft generated by Company Brain skill-audit. **Not yet human-approved** — a person on your team must review and approve before any AI agent relies on it._",
    "",
  );

  return parts.join("\n");
}
