/**
 * skill-audit CLI — the cold-outreach hook from the execution plan (§7.1/§7.2).
 *
 * Point it at a prospect's PUBLIC help-center URL; it crawls a handful of
 * articles, extracts procedure-shaped SKILL.md drafts with whichever LLM provider
 * is configured (free Gemini tier by default), and writes them to ./out/<host>/
 * along with an emailable AUDIT.md summary.
 *
 * Usage:
 *   npm run audit -- <help-center-url> [options]
 *
 * Options:
 *   --max <n>     max articles to crawl                 (default 8)
 *   --model <id>  override the model id (else uses CB_LLM_MODEL / provider default)
 *   --out <dir>   output directory                      (default ./out)
 *   --dry-run     crawl + assemble the prompt, but DON'T call the LLM (no key needed)
 *
 * Examples:
 *   npm run audit -- https://help.example.com --dry-run
 *   npm run audit -- https://support.acme.com --max 10
 */
import "dotenv/config";
import { writeFile, mkdir } from "node:fs/promises";
import { join } from "node:path";
import { crawlHelpCenter } from "../lib/crawl";
import { extractSkills, buildCorpus, SYSTEM_PROMPT } from "../lib/extract";
import { getLlmConfig } from "../lib/llm";
import { serializeSkill } from "../lib/skillmd";

interface Args {
  url: string;
  max: number;
  model: string | undefined;
  out: string;
  dryRun: boolean;
}

function parseArgs(argv: string[]): Args {
  let url = "";
  let max = 8;
  let model: string | undefined;
  let out = "out";
  let dryRun = false;

  for (let i = 0; i < argv.length; i++) {
    const arg = argv[i];
    if (arg === undefined) continue;
    if (arg === "--dry-run") dryRun = true;
    else if (arg === "--max") max = Number(argv[++i] ?? max) || max;
    else if (arg === "--model") model = argv[++i] ?? model;
    else if (arg === "--out") out = argv[++i] ?? out;
    else if (!arg.startsWith("--") && !url) url = arg;
  }
  return { url, max, model, out, dryRun };
}

function fail(msg: string): never {
  console.error(`\n✗ ${msg}\n`);
  process.exit(1);
}

async function main(): Promise<void> {
  const args = parseArgs(process.argv.slice(2));

  if (!args.url) {
    fail("Missing help-center URL.\n  Usage: npm run audit -- <help-center-url> [--max 8] [--dry-run]");
  }
  let base: URL;
  try {
    base = new URL(args.url);
  } catch {
    return fail(`Not a valid URL: ${args.url}`);
  }

  const cfg = getLlmConfig();

  console.log(`\n🧠 Company Brain — skill audit`);
  console.log(`   Target:   ${base.href}`);
  console.log(`   Model:    ${args.model ?? cfg.model}${cfg.hasKey ? "" : "  ⚠ no key"}`);
  console.log(`   Crawling (max ${args.max} articles, please wait)...\n`);

  const articles = await crawlHelpCenter(base.href, args.max, (m) => console.log(m));

  if (articles.length === 0) {
    fail(
      "No readable articles found. The site may be JavaScript-rendered (e.g. notion.site) " +
        "or block crawlers. Try a direct article URL, or a different help center.",
    );
  }
  console.log(`\n✓ Extracted readable text from ${articles.length} article(s).`);

  if (args.dryRun || !cfg.hasKey) {
    if (!cfg.hasKey && !args.dryRun) {
      console.log("\n⚠  No LLM API key found — showing a DRY RUN instead of calling the model.");
      console.log("   Add a free-tier key to .env (see .env.example), e.g. GEMINI_API_KEY=...\n");
    }
    const { text } = buildCorpus(articles);
    console.log("\n────────── SYSTEM PROMPT ──────────\n");
    console.log(SYSTEM_PROMPT);
    console.log("\n────────── CORPUS (first 1500 chars) ──────────\n");
    console.log(text.slice(0, 1500) + (text.length > 1500 ? "\n... [truncated]" : ""));
    console.log(
      `\n(model: ${args.model ?? cfg.model}; corpus ${text.length} chars / ${articles.length} articles)`,
    );
    console.log("\n✓ Dry run complete. No API call made.\n");
    return;
  }

  console.log(`\n🤖 Extracting skills with ${args.model ?? cfg.model}...`);
  const drafts = await extractSkills(articles, args.model);

  if (drafts.length === 0) {
    console.log("\n(No well-supported procedures found in this corpus — that's a valid, honest result.)\n");
    return;
  }

  const outDir = join(args.out, base.host);
  await mkdir(outDir, { recursive: true });

  for (const draft of drafts) {
    const skillDir = join(outDir, draft.slug);
    await mkdir(skillDir, { recursive: true });
    await writeFile(join(skillDir, "SKILL.md"), serializeSkill(draft), "utf8");
  }

  const summary = [
    `# Skill audit — ${base.host}`,
    "",
    `Generated by Company Brain from ${articles.length} public help-center article(s) using \`${args.model ?? cfg.model}\`.`,
    `**${drafts.length} draft skill(s).** None are human-approved yet — that's your team's call.`,
    "",
    "| Skill | Confidence | Sources |",
    "|---|---|---|",
    ...drafts.map((d) => `| ${d.title} | ${d.confidence ?? "—"} | ${d.sources.length} |`),
    "",
    "Each skill is in its own folder as a ready-to-use `SKILL.md` (Agent Skill format).",
  ].join("\n");
  await writeFile(join(outDir, "AUDIT.md"), summary, "utf8");

  console.log(`\n✓ Wrote ${drafts.length} skill(s) to ${outDir}/`);
  for (const d of drafts) {
    console.log(`   • ${d.title}  (${d.confidence ?? "?"} confidence, ${d.sources.length} source[s])`);
  }
  console.log(`\n📄 Summary to email the prospect: ${join(outDir, "AUDIT.md")}\n`);
}

main().catch((err) => {
  console.error("\n✗ Audit failed:", err instanceof Error ? err.message : err);
  process.exit(1);
});
